const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { chromium } = require("playwright");
const base = process.env.WORKBENCH_TEST_URL || "http://127.0.0.1:4174/";
const output = path.join(__dirname, "..", ".tmp", "drawing-qa");
const stable = (value) => JSON.stringify(value, (_, item) => item && typeof item === "object" && !Array.isArray(item)
  ? Object.keys(item).sort().reduce((result, key) => ({ ...result, [key]: item[key] }), {}) : item);
const alpha = (page, x, y) => page.locator("#noteCanvas").evaluate((canvas, point) => canvas.getContext("2d").getImageData(...point, 1, 1).data[3], [x, y]);
async function line(page, x1, y1, x2, y2) {
  const canvas = page.locator("#noteCanvas");
  await canvas.scrollIntoViewIfNeeded();
  const rect = await canvas.boundingBox();
  await page.mouse.move(rect.x + rect.width * x1, rect.y + rect.height * y1);
  await page.mouse.down();
  await page.mouse.move(rect.x + rect.width * x2, rect.y + rect.height * y2, { steps: 20 });
  await page.mouse.up();
}
(async () => {
  fs.mkdirSync(output, { recursive: true });
  const browser = await chromium.launch({ headless: true, channel: "msedge" });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true, hasTouch: true });
    await context.addInitScript(() => {
      if (!localStorage.getItem("workbenchlab-v1")) localStorage.setItem("workbenchlab-v1", JSON.stringify({ name: "TST.QAA", className: "TEST" }));
    });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", (error) => errors.push(error.message));
    await page.goto(`${base}?screenshot=1#home`);
    assert.equal(await page.locator(".save-reminder").count(), 0);
    assert.equal(await page.locator(".model-glossary").evaluate((el) => el.open), false);
    await page.locator(".model-glossary summary").click();
    assert.ok(await page.locator(".model-glossary p").isVisible());
    await page.locator(".model-glossary summary").click();
    assert.equal(await page.locator(".model-glossary p").isVisible(), false);
    await page.locator(".path-overview summary").click();
    await page.locator(".relief-map").scrollIntoViewIfNeeded();
    await page.waitForFunction(() => document.querySelector(".relief-map img").naturalWidth > 0);
    assert.equal(await page.locator(".map-pin").count(), 5);
    assert.equal(await page.locator('.map-pin[aria-disabled="true"]').count(), 4);
    await page.screenshot({ path: path.join(output, "map-desktop.png"), animations: "disabled" });
    await page.locator(".brand").evaluate((el) => el.click());
    await page.waitForFunction(() => scrollY === 0);
    await page.goto(`${base}?screenshot=1#lesson/warum-datenbanken`);
    await page.locator("[data-lesson-reading]").waitFor();
    await page.evaluate(() => scrollTo(0, 1000));
    const before = await page.evaluate(() => scrollY);
    await page.locator('.reading-tools [data-route^="notes/"]').evaluate((el) => el.click());
    await page.locator("#notebookEditor").waitFor();
    assert.equal(await page.getByRole("button", { name: "Zur Lerneinheit" }).count(), 0);
    await page.locator("[data-close-notes]").click();
    await page.locator("[data-lesson-reading]").waitFor();
    await page.waitForFunction((top) => Math.abs(scrollY - top) < 2, before);
    await page.locator('.reading-tools [data-route^="notes/"]').evaluate((el) => el.click());
    await page.locator("#notebookEditor").fill("Meine Skizze einer Tabellenbeziehung.");
    await page.locator("#noteDrawingTab").click();
    await page.locator("#drawingWidth").selectOption("20");
    await line(page, 0.2, 0.5, 0.8, 0.5);
    assert.ok(await alpha(page, 600, 360) > 0);
    await page.locator('[data-draw-tool="erase"]').click();
    await line(page, 0.5, 0.3, 0.5, 0.7);
    assert.equal(await alpha(page, 600, 360), 0);
    assert.ok(await alpha(page, 360, 360) > 0);
    await page.locator('[data-draw-action="undo"]').click();
    assert.ok(await alpha(page, 600, 360) > 0);
    await page.locator('[data-draw-action="redo"]').click();
    assert.equal(await alpha(page, 600, 360), 0);
    await page.locator('[data-pen-color="#175fa4"]').click();
    await line(page, 0.1, 0.2, 0.6, 0.2);
    const pixel = await page.locator("#noteCanvas").evaluate((canvas) => Array.from(canvas.getContext("2d").getImageData(360, 144, 1, 1).data));
    assert.ok(pixel[2] > pixel[0] && pixel[3] > 0);
    await page.reload();
    await page.locator("#noteDrawingTab").click();
    assert.equal(await alpha(page, 600, 360), 0);
    assert.ok(await alpha(page, 360, 360) > 0);
    await page.screenshot({ path: path.join(output, "drawing-desktop.png"), animations: "disabled" });
    const png = page.waitForEvent("download");
    await page.locator('[data-draw-action="download"]').click();
    assert.ok((await png).suggestedFilename().endsWith(".png"));
    await page.locator("#backupButton").click();
    const json = page.waitForEvent("download");
    await page.locator("#exportProgressButton").click();
    const file = path.join(output, "drawing-export.json");
    await (await json).saveAs(file);
    const exported = JSON.parse(fs.readFileSync(file, "utf8"));
    assert.equal(exported.formatVersion, 5);
    assert.equal(exported.data.noteDrawings["warum-datenbanken"].length, 3);
    const { integrity, ...body } = exported;
    assert.equal(integrity.digest, crypto.createHash("sha256").update(stable(body)).digest("hex"));
    await page.locator("#backupCloseButton").click();
    page.once("dialog", (dialog) => dialog.accept());
    await page.locator('[data-draw-action="clear"]').click();
    assert.equal(await alpha(page, 360, 360), 0);
    await page.locator("#backupButton").click();
    page.once("dialog", (dialog) => dialog.accept());
    await page.locator("#progressFileInput").setInputFiles(file);
    await page.locator("#backupDialog").waitFor({ state: "hidden" });
    assert.ok(await alpha(page, 360, 360) > 0);
    await page.locator("#noteTextTab").click();
    assert.equal(await page.locator("#notebookEditor").inputValue(), "Meine Skizze einer Tabellenbeziehung.");
    const legacy = structuredClone(exported);
    legacy.formatVersion = 4;
    delete legacy.data.noteDrawings;
    const { integrity: legacyIntegrity, ...legacyBody } = legacy;
    legacy.integrity.digest = crypto.createHash("sha256").update(stable(legacyBody)).digest("hex");
    const legacyFile = path.join(output, "legacy-v4.json");
    fs.writeFileSync(legacyFile, JSON.stringify(legacy));
    await page.locator("#backupButton").click();
    page.once("dialog", (dialog) => dialog.accept());
    await page.locator("#progressFileInput").setInputFiles(legacyFile);
    await page.locator("#backupDialog").waitFor({ state: "hidden" });
    assert.equal(await page.locator("#notebookEditor").inputValue(), "Meine Skizze einer Tabellenbeziehung.");
    await page.locator("#noteDrawingTab").click();
    assert.equal(await alpha(page, 360, 360), 0);
    await page.locator("#backupButton").click();
    page.once("dialog", (dialog) => dialog.accept());
    await page.locator("#progressFileInput").setInputFiles(file);
    await page.locator("#backupDialog").waitFor({ state: "hidden" });
    await page.setViewportSize({ width: 390, height: 844 });
    for (const theme of ["dark", "light"]) {
      if (await page.locator("html").getAttribute("data-theme") !== theme) await page.locator("#themeToggleButton").click();
      await page.locator("#appearanceButton").click();
      await page.locator('[data-font-size="20"]').click();
      await page.locator("#appearanceDoneButton").click();
      await page.locator("#noteDrawingTab").click();
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.locator("#noteCanvas").scrollIntoViewIfNeeded();
      await page.waitForFunction(() => !document.querySelector("#toastRegion").children.length);
      await page.screenshot({ path: path.join(output, `drawing-${theme}-mobile.png`), animations: "disabled" });
    }
    await page.goto(`${base}?screenshot=1#home`);
    await page.locator(".path-overview summary").click();
    await page.locator(".relief-map").scrollIntoViewIfNeeded();
    await page.waitForFunction(() => document.querySelector(".relief-map img").naturalWidth > 0);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: path.join(output, "map-mobile.png"), animations: "disabled" });
    assert.deepEqual(errors, []);
    await context.close();
    console.log("PASS: uncluttered footer, glossary toggle, map, same-route home scroll, notes close/scroll restoration, drawing pixels, eraser, undo/redo, color, reload, PNG, JSON roundtrip and desktop/mobile.");
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
